<?php

namespace backend\assets;

use yii\web\AssetBundle;
use yii\web\View;

/**
 * Main backend application asset bundle.
 */
class AppAssetLogin extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->basePath = '@app/backend/web';
        $this->css = [
           'css/style.css'
        ];
        $this->depends = [
            'yii\web\YiiAsset',
            'yii\bootstrap\BootstrapAsset',
            'yii\bootstrap\BootstrapPluginAsset'
        ];
        $this->jsOptions['position']=View::POS_HEAD;

    }


}
