<?php

namespace frontend\assets;


use yii\web\AssetBundle;
use yii\web\View;

/**
 * Main frontend application asset bundle.
 */
class AppAssetLogin extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->basePath = '@app/frontend/web';
        $this->css = [
           /* 'css/site.css',*/
            'css/style.css'
        ];
        $this->js = [
            'js/ace-extra.min.js',

        ];
        $this->depends = [
            'yii\web\YiiAsset',
            'yii\bootstrap\BootstrapAsset',
            'yii\bootstrap\BootstrapPluginAsset'
        ];
        $this->jsOptions['position']=View::POS_HEAD;

    }
}
